### ISSUE TITLE
local file

### ISSUE THREAD

**Issue by gmoulard** [tomMoulard/make-my-server#1]
hello 

dans ta ligne 

https://github.com/tomMoulard/make-my-server/blob/d0f1e504a245681da91f1e0fe00affb2235c4045/docker-compose.yml#L128

tu fait référence a un fichier sur ton serveur, tu ferais pas mieux d'utiliser la référence a un fichier dans le GIT ? 

dans mon dokerfile https://github.com/gmoulard/pi-appliance/blob/master/docker-apache/dockerfile.php.mariadb
je fait un truc 
COPY etc/apache2/sites-available/* /etc/apache2/sites-available/

qui intergre alors les fichiers de https://github.com/gmoulard/pi-appliance/tree/master/docker-apache/etc/apache2/sites-available

G.

**Comment by tomMoulard** [comment]
Oui en effet,
C'est ce que j'ai fait pour [nginx](https://github.com/tomMoulard/make-my-server/blob/d0f1e504a245681da91f1e0fe00affb2235c4045/docker-compose.yml#L116). Et je compte enlever la configuration pour `cyprine`.

## Pour `nginx`
J'ai mis: 
```docker-compose
    volumes:
      - './nginx:/etc/nginx/conf.d'
```
et tu peux faire 
```bash
$ ls nginx
nginx.conf www
```
