### ISSUE TITLE
I tried to get the gitlab part to work but it didnt work.

### ISSUE THREAD

**Issue by thepenguinthatwants** [tomMoulard/make-my-server#2]
So I erased everything leaving only the gitlab and gitlab runner. Also left the gitlab/config untouched.

runner_1  | ERROR: Failed to load config stat /etc/gitlab-runner/config.toml: no such file or directory  builds=0

Does need all the other things to get gitlab started?

**Comment by tomMoulard** [comment]
Hi,
Gitlab CI/CD is in a work in progress state, thus it is not fully working.
I have made a few changes to have a configuration file, but i cannot find a way to link the runner with gitlab([#074e6d8](https://github.com/tomMoulard/make-my-server/commit/074e6d8c8e131ff37085f22c7a198edb1d6ff70a) and [#6afb3c0](https://github.com/tomMoulard/make-my-server/commit/6afb3c08a60a44e983a9556c837c6118bff3f465)).
But if you run `docker-compose up -d traefik gitlab` gitlab will be available.

**Comment by tomMoulard** [comment]
To follow up on this, it is now a working feature thanks to this [commit](https://github.com/tomMoulard/make-my-server/commit/b63052b8eff47be66a384be05b375d878d5782e9).
Thanks for your feedback
