### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by D0tty** [tomMoulard/make-my-server#3]
This might be a good thing to add a letsencrypt service with a shared volume to have SSL certificates for every subdomain you have for your services!

Keep the good work ! 💯

**Comment by tomMoulard** [comment]
Thanks to [traefik](http://traefik.io) for providing the ssl termination and encryption for all of subdomains with a quite simple [configuration](https://github.com/tomMoulard/make-my-server/blob/master/traefik/traefik.toml#L32-L39).

Thanks a lot to you for your feedback \o/
