### ISSUE TITLE
Use the .env file

### ISSUE THREAD

**Issue by D0tty** [tomMoulard/make-my-server#4]
I see that you use `export VAR=value` but you can use the `.env` file [documentation](https://docs.docker.com/compose/environment-variables/)

And you can then provide a `.env.example` file on the repository to centralize all environnent variables

**Comment by tomMoulard** [comment]
Since you can actually use this project with only one environment variable, i do not think this is a huge matter.
Moreover, it might create confusion in the file directory to have a file for only one variable

**Comment by tomMoulard** [comment]
A workaround might be to do something like
```bash
cat > .env << EOF
SITE=
HASHED_PASSWORD=
EOF
```
